#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn "${TERMINAL:-alacritty}" # use your $TERMINAL with xterm as fallback

# dmenu launcher
hc keybind $Mod-d spawn dmenu_run -i -nb '#191919' -nf '#fea63c' -sb '#fea63c' -sf '#191919' -fn 'NotoMonoRegular:bold:pixelsize=14'
# rofi launcher
hc keybind $Mod-Shift-Return spawn rofi -show run

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..10} )
tag_keys=( {1..10} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    # horizontal tiling as standard
    hc set_layout horizontal
    hc set default_frame_layout 1
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" chain , move_index "$i" , use_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-d set_attr clients.focus.decorated toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

#reset prior to setting the theme
hc attr theme.reset 1

# Attribute
hc attr theme.active.color '#6790EB'
hc attr theme.active.inner_color '#141414'
hc attr theme.active.outer_color '#6790EB'
hc attr theme.background_color '#141414'
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.inner_color black
hc attr theme.inner_width 1
hc attr theme.normal.color '#141414'
hc attr theme.urgent.color orange

# Set
hc set always_show_frame 1
hc set focus_follows_mouse 1
hc set frame_border_active_color '#6790EB'
hc set frame_border_normal_color '#141414'
hc set frame_bg_normal_color '#141414'
hc set frame_bg_active_color '#000000'
hc set frame_border_width 3
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 5
hc set frame_padding 0
hc set mouse_recenter_gap 0
hc set smart_frame_surroundings 1
hc set smart_window_surroundings 0
hc set tree_style '╾│ ├└╼─┐'
hc set window_gap 5

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients

# assign applications to workspaces or tags -using numbers for tags
# These are used then -- tag_names=( {1..10} )

hc rule class~'(Navigator|Firefox|Vivaldi-stable|Vivaldi-snapshot|Chromium|Google-chrome|Brave|Brave-browser)' tag=1 switchtag=on focus=on
hc rule class~'(navigator|firefox|vivaldi-stable|vivaldi-snapshot|chromium|google-chrome|brave|brave-browser)' tag=1 switchtag=on focus=on
hc rule class~'(Atom|Subl|Geany|Brackets|Code-oss|Code|TelegramDesktop|Discord)' tag=2 switchtag=on focus=on
hc rule class~'(atom|subl|geany|brackets|code-oss|code|telegramdesktop|discord)' tag=2 switchtag=on focus=on
hc rule class~'(Inkscape|Nomacs|Ristretto|Nitrogen|Feh)' tag=3 switchtag=on focus=on
hc rule class~'(inkscape|nomacs|ristretto|nitrogen|feh)' tag=3 switchtag=on focus=on
hc rule class~'(Gimp)' tag=4 switchtag=on focus=on
hc rule class~'(gimp)' tag=4 switchtag=on focus=on
hc rule class~'(Meld|org.gnome.Meld)' tag=5 switchtag=on focus=on
hc rule class~'(meld|org.gnome.meld)' tag=5 switchtag=on focus=on
hc rule class~'(Vlc|Mpv)' tag=6 switchtag=on focus=on
hc rule class~'(vlc|mpv)' tag=6 switchtag=on focus=on
hc rule class~'(VirtualBox Manager|VirtualBox Machine|Vmplayer)' tag=7 switchtag=on focus=on
hc rule class~'(virtualbox manager|virtualbox machine|vmplayer)' tag=7 switchtag=on focus=on
hc rule class~'(Thunar|Nemo|Caja|Nautilus|org.gnome.Nautilus|Pcmanfm|Pcmanfm-qt)' tag=8 switchtag=on focus=on
hc rule class~'(thunar|nemo|caja|nautilus|org.gnome.nautilus|pcmanfm|pcmanfm-qt)' tag=8 switchtag=on focus=on
hc rule class~'(Evolution|Geary|Mail|Thunderbird)' tag=9 switchtag=on focus=on
hc rule class~'(evolution|geary|mail|thunderbird)' tag=9 switchtag=on focus=on
hc rule class~'(Spotify|Pragha|Clementine|Deadbeef|Audacious)' tag=10 switchtag=on focus=on
hc rule class~'(spotify|pragha|clementine|deadbeef|audacious)' tag=10 switchtag=on focus=on

# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
#panel=~/.config/herbstluftwm/panel.sh
#[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
#for monitor in $(hc list_monitors | cut -d: -f1) ; do
#    # start it on each monitor
#    "$panel" "$monitor" &
#done

#launching xmobar
#~/.config/herbstluftwm/xmobar &

#room for polybar on both monitors
#single polybar at top
hc pad 0 30
#second polybar at bottom
#hc pad 0 30 0 30 0
#single polybar at top
#hc pad 1 30
#second polybar at bottom
#hc pad 1 30 0 30 0

#launching polybar
~/.config/polybar/launch.sh

#Autostart applications
pkill -u $USER '^picom$'
picom  --config $HOME/.config/picom/picom.conf &
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/xfce4/notifyd/xfce4-notifyd &

xsetroot -solid '#000000'
xsetroot -cursor_name left_ptr &

#keybindings are in config of sxhkd - interchangeable with other TWM
#sxhkd -c ~/.config/herbstluftwm/sxhkd/sxhkdrc &

nitrogen --restore &
#feh --bg-fill $HOME/.config/herbstluftwm/wall.png
picom -b &
lxpolkit &
mpd &
nm-applet &
#volumeicon &
xfce4-power-manager &
#numlockx on &
urxvtd -q -o -f &
emacs --daemon &
